### ISSUE TITLE
Running telogator using zebrafish genome

### ISSUE THREAD

**Issue by Jokendo-collab** [zstephens/telogator2#4]
I find this tools interesting and I would like to use it in my zebrafish assembly. How can I generate a `telogator.fa` for my zebrafish data? I see it is loading human `telogator.fa` and this could not work well with my data. I look forward to your advise on how to do this.

**Comment by zstephens** [comment]
Greetings! I just added a `make_telogator_ref.py` script to the repository, which should allow you to make a subtelomere reference that Telogator2 can accept via the `-t` input option. Example usage:

`python make_telogator_ref.py -i input-ref.fa -o output-telogator-ref.fa -s zebrafish`

Note that if zebrafish has different telomere repeats (or variant repeats) than human, you might need to make an alternate kmers.tsv file.

**Comment by zstephens** [comment]
Closing this for now, feel free to reopen if you have additional questions.
