### ISSUE TITLE
Telogator2 performance across different sequencing coverage

### ISSUE THREAD

**Issue by niyati1211** [zstephens/telogator2#8]
Hello,

I have a question regarding the performance of Telogator2 under varying coverage. While Figure 10 of your paper illustrates that the number of identified telomere alleles increases with higher coverage, I was wondering if you had conducted any tests to assess how the accuracy of the estimates changes with coverage. Specifically, is there an observed bias/trend?

I apologize if this is not the best platform to ask, but before proceeding with my analyses, I’d like to better understand how coverage might influence the estimate itself.

Any insight would be helpful!

Thank you!!

**Comment by zstephens** [comment]
At one point we had a figure that showed the variance of ATL values at the same coverage points as the #alleles plot. I don't recall the precise values but the results were as expected in that the variance increases a lot as coverage gets lower. In older experiments (that predate Telogator2) we tested simulated data and found that at ~5-10x coverage the average error in TL measurement was around a kilobase, at 10-20x range it decreased to a few hundred bp, and at 30+x was maybe 100bp. Though real data is not going to be as uniformly distributed across alleles, and alleles with lower read counts are going to be rougher estimates.

**Comment by niyati1211** [comment]
Thank you, this is really helpful!
