### ISSUE TITLE
Unexpected long time running

### ISSUE THREAD

**Issue by chengy1128** [zstephens/telogator2#9]
Hello Zachary,

Thank you for developing and maintaining Telogator2! I’m currently analyzing a nanopore sequence however I’ve noticed that the runtime for processing this file is over 20 minutes on the clustering step.
 The command I used is: 
```
python telogator2.py -i "$input_file" -o "$output_subdir" --minimap2 "$MINIMAP2_PATH" -r ont -n 5 -tt 0.100 --collapse-hom 1000
```
Here is where I get stuck:
```
using default telogator subtel reference
using default telomere kmers
getting reads with at least 8 matches to CCCTAACCCTAA... (35 sec)
 - 4473 --> 3562 reads
 - (72054501 bp) --> (62926142 bp)
filtering by read length (>4000bp)... (0 sec)
 - 3562 --> 3414 reads
getting telomere repeat composition... (166 sec)
 - 3414 --> 2890 reads
 - (489 reads removed for ending in < 500bp tel sequence)
 - (14 reads removed for ending in > 200bp non-tel sequence)
 - (21 reads removed for ending in < 1000bp subtel sequence)
initial clustering of all reads...
```

**Comment by zstephens** [comment]
Greetings! Indeed the software is very compute-intensive. For datasets with several thousand telomere reads it's expected that it will take several hours to run. There are two main parameters for adjusting performance:

`-p` how many parallel processes to use during clustering steps. By default this is 4, and you can increase it to as many cpus as you have available. When processing large datasets in a HPC environment I typically set this to 16 or 32.

`-d` downsample reads. E.g. in your data you have 2890 telomere reads going into clustering, so if you set `-d 2000` it would randomly downsample reads to that amount, speeding up results.

Hope this helps!

**Comment by chengy1128** [comment]
> Greetings! Indeed the software is very compute-intensive. For datasets with several thousand telomere reads it's expected that it will take several hours to run. There are two main parameters for adjusting performance:
> 
> `-p` how many parallel processes to use during clustering steps. By default this is 4, and you can increase it to as many cpus as you have available. When processing large datasets in a HPC environment I typically set this to 16 or 32.
> 
> `-d` downsample reads. E.g. in your data you have 2890 telomere reads going into clustering, so if you set `-d 2000` it would randomly downsample reads to that amount, speeding up results.
> 
> Hope this helps!

Thanks!
